language: python
install:
  - pip install .
script: python -m unittest discover tests
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "nc6J3ymJdYOEgDiU72frwXNffhO2eKXdSHn1tHs2q0CMLZPPi+2jVD61oqab+8sxrIHWKLtzwPINI9+locp260J2/EKFXFFiXcvzU8lbECnDAucPw3ZBT00nurdQ52TCfJmklxztkCa1fDfmiY8CYexICQu2qqx9RjDoCpcpVhvJ/1W6taGzQHmZQc+iYD7DjffGI2GK7qU1qDF77+V1b9KFjhSnHewYy2iiiM+vVsOzXaw6n+Hzi4k73uOGvsLm2xF8kXdWJ+lZJ89DWLCwhQnmv5/acDj4p5hinEITTtmFRz546lavJrRcHAsXI10EH3oF4C+w5/2518t0h+QdqUZRpQ2f+2cqrlqeOcN3QU1RleegCjepni6wp+kGRPBrMaG0Op2mLYuhpIsBIBrvvL9QmzQ5qgoRNhrQhDf8OMV5KRDcN1NkjvfC63ZWphYR93KZ83eY+YgrhX1JhpEtHbFaSMSq2Bh/uVVxS34Pt+TYu/3A7+ImxjlnGnAG/GTozvMmM1jmpiXOt/KMBSvU90JJIuwHd4n3ksi+NILBlv3TJKIBdZBDL+Z2Y+L3aI8Uei2hgBRpZt06iMXytHPFtLS7oKMDHBzRO/WUWNVvmsYIX8Usevfi/oCzOsmqA6DUX3hE5a5SQPD/8BdmPKEPAb7QfUEKYAZVA7djMS1hQII="
